In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
arr = np.arange(1, 21)
vector = 2 ** arr / arr
print(vector)

[2.00000000e+00 2.00000000e+00 2.66666667e+00 4.00000000e+00
 6.40000000e+00 1.06666667e+01 1.82857143e+01 3.20000000e+01
 5.68888889e+01 1.02400000e+02 1.86181818e+02 3.41333333e+02
 6.30153846e+02 1.17028571e+03 2.18453333e+03 4.09600000e+03
 7.71011765e+03 1.45635556e+04 2.75941053e+04 5.24288000e+04]


**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
i = np.arange(0, 6)
vector = 0.1 ** (3 * i) * 0.2 **(4 * i)
print(vector.sum())

1.00000160000256


**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
matrix = np.ones((8, 8))
matrix[1::2,::2] = 0
matrix[::2,1::2] = 0
print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
r = (X[::1,::2] ** 2 + X[::1,1::] ** 2) ** (0.5)
phi = np.arctan(X[::1,1::] / X[::1,::2])
polar = np.concatenate((r, phi), axis=1)
print(polar)

[[0.71350938 1.17557185]
 [0.33043383 1.515982  ]
 [0.06325604 0.48601209]
 [0.82226554 0.79220593]
 [0.74136398 0.05210542]]


**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
ans = np.argmax(X)
print(ans // 10, ans % 10)

0 2


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
print(X[np.argmin(((X[:, 0] ** 2 - y[0][0]) ** 2 + (X[:, 1] - y[0][1]) ** 2) ** 0.5)])

[0.75628567 0.41051669]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
def function(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    if 0 <= x < 2:
        return x + 6
    if x >= 2:
        return x ** 2 + 4 * x - 4
    
    
x = np.arange(-3, 4)
print(list(map(function, x)))

[9, 6, 5, 6, 7, 8, 17]


**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))
ans = X - np.mean(X, axis=1, keepdims=True)
print(X)
print(np.mean(ans, axis=1))

[[0.58061853 0.85168143 0.72643643 0.27304644 0.96348519 0.76035877
  0.26179791 0.9692438  0.92740115 0.2263973 ]
 [0.65879424 0.50717332 0.57872795 0.0894775  0.48407574 0.97658562
  0.16490079 0.42994322 0.57674413 0.99473134]
 [0.48779011 0.14190066 0.64699497 0.18625945 0.25351772 0.48344308
  0.95887156 0.96526727 0.50857411 0.04757806]
 [0.00805844 0.00881515 0.94529991 0.13474056 0.68942243 0.64449738
  0.617998   0.85314539 0.71151609 0.12899615]
 [0.68552807 0.31112518 0.22768514 0.05269062 0.71024402 0.42026335
  0.94176533 0.47262979 0.52973757 0.3685298 ]
 [0.96022064 0.15990465 0.77659666 0.40024938 0.83038361 0.50016755
  0.96020846 0.6451311  0.781758   0.46174479]
 [0.33125126 0.25230616 0.63621341 0.18673741 0.97550685 0.44564672
  0.21723949 0.84555861 0.78010571 0.54942658]
 [0.33049539 0.83112061 0.4376097  0.85206491 0.96747029 0.92844226
  0.35868387 0.41657865 0.94021613 0.19138387]
 [0.03122708 0.47063396 0.14874436 0.38978549 0.6747041  0.46696871
  0.22421367

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
print(np.mean(X), np.var(X))

4.924445336092377 3.9197077575878265


**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
row = np.arange(5)
col = row.reshape(5,1)
matrix = row + col
matrix %= 5
print(matrix)

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    val = s * np.random.random(c)
    ans = np.argmin((np.cumsum(x) <= val.reshape(-1,1)), axis=1)
    return ans

sample([50, 3, 1, 7, 20], 5)

array([4, 4, 4, 0, 0], dtype=int64)